In [1]:
import numpy as np
np.__version__

'2.1.3'

# Creating Array using list


In [2]:
a = [1,2,3,4]  #list

In [3]:
np.array(a)

array([1, 2, 3, 4])

In [4]:
arr1 = np.array(a)

In [5]:
type(arr1)

numpy.ndarray

In [6]:
b = [True, False, False, True, True, False]
print(type(b))

arr2 = np.array(b)
print(type(arr2))
print(arr2)

<class 'list'>
<class 'numpy.ndarray'>
[ True False False  True  True False]


In [7]:
c = [True, 0, 9.8, True, -10, False]
print(type(c))

arr3 = np.array(c)
print(type(arr3))
print(arr3) 

<class 'list'>
<class 'numpy.ndarray'>
[  1.    0.    9.8   1.  -10.    0. ]


In [8]:
float(False)

0.0

# Creating array without using list

In [9]:
a = np.zeros(5)
print(a)
print(type(a))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones(shape=5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [15]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.eye(1)

array([[1.]])

In [18]:
a = [1,2,3,4,5]

In [19]:
[i+2 for i in a]

[3, 4, 5, 6, 7]

In [20]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [21]:
a + 2

array([3, 4, 5, 6, 7])

In [22]:
a - 10

array([-9, -8, -7, -6, -5])

In [23]:
a / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

# Creating array- using arange function

In [24]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
a = np.arange(31,40)
a

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [29]:
print(a[0])

31


In [30]:
print(a[8])

39


**Reshaping array**

In [31]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
b = np.arange(50,65).reshape(3,5)
print(b)

[[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]]


In [34]:
b.shape

(3, 5)

In [35]:
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


# Array slicing

In [36]:
a = np.arange(0,20).reshape(4,5)
print(a)
print(a.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [37]:
a[0,:]

array([0, 1, 2, 3, 4])

In [38]:
a[0,2]

np.int64(2)

In [39]:
print(a[0,2])

2


In [40]:
a[1,3:]

array([8, 9])

In [41]:
a[1,3:5]

array([8, 9])

In [42]:
a.shape

(4, 5)

In [43]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [44]:
a[3,:]

array([15, 16, 17, 18, 19])

In [45]:
a[3,1:4]

array([16, 17, 18])

In [46]:
a[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [47]:
t = list(range(10))
t

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
t[2:5]

[2, 3, 4]

In [49]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [50]:
a[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [51]:
# Assignment
# Get 0, 1, 5, 6 from this above array

In [53]:
#np.arange(0,10,4)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
a[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [57]:
a[1,0:2]

array([5, 6])

In [70]:
# Assignment
# Get 12,13,14 and 17,18,19 from this above array

In [69]:
a[2:4,2:6]

array([[12, 13, 14],
       [17, 18, 19]])

# Link to Python Data Science Handbook
Fork this repo and then clone to your local

https://github.com/jakevdp/PythonDataScienceHandbook